project:
  type: website
  output-dir: _site
  
website:
  title: "Title Text"
  # description: "Description Text"

  description: "Some description"
  site-url: https://github.com/wiesehahn/quarto_website_template/index.html
  repo-url: https://github.com/wiesehahn/quarto_website_template
  favicon: /images/favicon.png
  image: /images/logo.png
  open-graph: true
  twitter-card:
    creator: '@JensWiesehahn'
  search: false
  # reader-mode: true
  navbar:
  # title: false
    logo: /images/logo.png
    logo-alt: "Website logo image"
    # logo-href: https://wiesehahn.github.io/
    collapse: true
    
    left:
      - href: content/index.qmd
        text: "Menu Title" # Menu title of document, automatically from document title if not provided

    # add sections here
      # - href: content/subpage.qmd
      #   text: "Subpage_Title"
      
    right:
      - icon: triangle-fill
        href: https://wiesehahn.github.io
      - icon: github
        href: https://github.com/wiesehahn
      - icon: twitter
        href: https://twitter.com/JensWiesehahn
      - icon: mastodon
        href: https://elk.zone/fosstodon.org/@JensWiesehahn
      - icon: envelope-fill
        href: mailto::wiesehahn.jens@gmail.com

  page-footer:
    border: false
    left: "Â© 2024, [Jens Wiesehahn](https://wiesehahn.github.io)"
    right:
      - icon: github
        href: https://github.com/wiesehahn/wiesehahn.github.io

format:
  html: # (https://quarto.org/docs/reference/formats/html.html)
    theme: [litera, assets/custom_theme.scss]
    mainfont: Nunito
    toc: true
    smooth-scroll: true
    highlight: arrow
    page-layout: full
    code-copy: hover
    code-overflow: wrap
    code-line-numbers: false
    grid:
      sidebar-width: 250px
      body-width: 1200px
      margin-width: 250px

tbl-cap-location: top

# bibliography: ../references.bib


